# Generated by Django 3.0.7 on 2023-12-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('uid', models.AutoField(db_column='uid', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='firstname', max_length=25)),
                ('lastname', models.CharField(db_column='lastname', max_length=25)),
                ('username', models.CharField(db_column='username', max_length=25)),
                ('password', models.CharField(db_column='password', max_length=25, null=True)),
                ('address', models.CharField(db_column='address', max_length=100, null=True)),
                ('dob', models.IntegerField(db_column='dob', null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
    ]
