# Generated by Django 3.0.7 on 2023-12-26 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='active',
            field=models.BooleanField(db_column='active', default=True, null=True),
        ),
    ]
